#chrome,firefox,edge, chrome
browser=chrome
appUrl=http://localhost:100
userid=admin
password=admin

invalidUN=


dbname=
dbhost=
dbuserid=
dbpassword=

Base_URL_PD=https://duracell-cloud-appservice-testing.azurewebsites.net

authenticate=/api/membership/authenticate

installer_list=/api/installer/installerlist

language_list=/api/membership/language/list

TZ = /api/installation/Timezones

B_regi = /api/register/Installation

EV_regi_Existing = /api/installation/updateEV

install_list=/api/installation/list